"""Change to Notifications

Revision ID: 8f5167f2df8a
Revises: 00d931d7bcee
Create Date: 2026-07-30 21:48:05.727617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5167f2df8a'
down_revision: Union[str, Sequence[str], None] = '00d931d7bcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'message')
    # ### end Alembic commands ###
